# -*- coding: utf-8 -*-
"""tugas dibimbing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sv5NBlPWbnJeO_zbTxQM8_paUCwzf2LK
"""

import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/dibimbing/2017.csv')

data

data.info()

data.isna().sum()

data.describe()

data['Happiness.Rank'].describe()

for column in data.columns:
    if data[column].dtype == 'object':
        # Jika kolom bertipe objek (teks), isi dengan modus (nilai yang paling sering muncul)
        mode_value = data[column].mode()[0]
        data[column] = data[column].fillna(mode_value)
    else:
        # Jika kolom numerik, isi dengan nilai rata-rata
        mean_value = data[column].mean()
        data[column] = data[column].fillna(mean_value)

data.isna().sum()

data.info()

# Mengecek apakah ada duplicate di seluruh kolom
check_duplicate = data.duplicated().sum()

print(f"Jumlah data yang duplikat = {check_duplicate}")

# Handling duplicate
data = data.drop_duplicates()

#tapi disni data saya sudah tidak ada data yang duplikat

# Mengecek duplicate setelah di-handle
handle_duplicate = data.duplicated().sum()

print(f"Jumlah data yang duplikat = {handle_duplicate}")